# 1) testa portas do pr처prio localhost
- name: Verificando conex찾o nas portas do MONITORAMENTO (localhost -> localhost)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Testa localhost:{{ item }}
      ansible.builtin.wait_for:
        host: "localhost"
        port: "{{ item }}"
        timeout: 1
        state: started
      loop:
        - 22
        - 3000
        - 5432
        - 8080
        - 9090
        - 9100
      ignore_errors: yes


# 2) testa do localhost para TODOS os hosts dos grupos onprimise e aws_ec2 nas portas 22,5432,9100
- name: Verificando conex찾o nas portas dos NODES LINUX (localhost -> onprimise/aws_ec2)
  hosts: localhost
  gather_facts: no
  vars:
    targets: "{{ (groups['onprimise'] | default([])) + (groups['aws_ec2'] | default([])) }}"
    ports: [22, 5432, 9100]
  tasks:
    - name: Testa hosts linux
      ansible.builtin.wait_for:
        host: "{{ hostvars[item.0].ansible_host | default(item.0) }}"
        port: "{{ item.1 }}"
        timeout: 1
        state: started
      loop: "{{ targets | product(ports) | list }}"
      ignore_errors: yes


# 3) testa do localhost para TODOS os hosts do grupo aws_rds apenas na porta 5432
- name: Verificando conex찾o nas portas dos NODES PROVISIONADOS (localhost -> aws_rds)
  hosts: localhost
  gather_facts: no
  vars:
    targets: "{{ groups['aws_rds'] | default([]) }}"
    ports: [5432]
  tasks:
    - name: Testa hosts postgres provisionados
      ansible.builtin.wait_for:
        host: "{{ hostvars[item.0].ansible_host | default(item.0) }}"
        port: "{{ item.1 }}"
        timeout: 1
        state: started
      loop: "{{ targets | product(ports) | list }}"
      ignore_errors: yes
