- name: Verificar usuários e permissões no Postgres (usando .pgpass)
  hosts: localhost
  gather_facts: no
  vars:
    db_host: "pg-db1" # mude p/ seu host/IP/endpoint
    db_port: 5432
    db_name: "postgres"
    admin_user: "postgres"

    user_pt: "powertuning"
    user_pgwatch: "pgwatch2"

  tasks:
    # ---------- POWERTUNING ----------
    - block:
        - name: "Teste connection"
          community.postgresql.postgresql_query:
            login_host: "{{ db_host }}"
            login_port: "{{ db_port }}"
            login_user: "{{ admin_user }}"
            login_db: "{{ db_name }}"
            query: "SELECT 1 "
          register: conntest
          changed_when: false
      rescue:
        - name: " Teste de conexão falhou"
          ansible.builtin.fail:
            msg: "Não foi possível conectar ou consultar o banco {{ db_host }}:{{ db_port }} como {{ admin_user }}"

    - block:
        - name: "[powertuning] Existe?"
          when: pt_exists.rowcount|int > 0
          community.postgresql.postgresql_query:
            login_host: "{{ db_host }}"
            login_port: "{{ db_port }}"
            login_user: "{{ admin_user }}"
            login_db: "{{ db_name }}"
            query: "SELECT 1 FROM pg_roles WHERE rolname = %(u)s"
            named_args: { u: "{{ user_pt }}" }
          register: pt_exists
          changed_when: false
          failed_when: pgw_exists.rowcount | int == 0
    - rescue:
        - name: "[powertuning] Falha ao conectar ou consultar o banco"
          ansible.builtin.fail:
            msg: "Não foi possível conectar ou consultar o banco {{ db_host }}:{{ db_port }} como {{ admin_user }}"

    - name: "[powertuning] É membro de pg_monitor?"
      when: pt_exists.rowcount|int > 0
      community.postgresql.postgresql_query:
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ admin_user }}"
        login_db: "{{ db_name }}"
        query: "SELECT pg_has_role(%(u)s, 'pg_monitor', 'member') AS is_member"
        named_args: { u: "{{ user_pt }}" }
      register: pt_pgmonitor

    - name: "[powertuning] Tem atributo CREATEROLE?"
      when: pt_exists.rowcount|int > 0
      community.postgresql.postgresql_query:
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ admin_user }}"
        login_db: "{{ db_name }}"
        query: "SELECT rolcreaterole FROM pg_roles WHERE rolname = %(u)s"
        named_args: { u: "{{ user_pt }}" }
      register: pt_createrole

    - name: "[powertuning] Tem atributo LOGIN?"
      when: pt_exists.rowcount|int > 0
      community.postgresql.postgresql_query:
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ admin_user }}"
        login_db: "{{ db_name }}"
        query: "SELECT rolcanlogin FROM pg_roles WHERE rolname = %(u)s"
        named_args: { u: "{{ user_pt }}" }
      register: pt_login

    # ---------- PGWATCH2 ----------
    - name: "[pgwatch2] Existe?"
      community.postgresql.postgresql_query:
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ admin_user }}"
        login_db: "{{ db_name }}"
        query: "SELECT 1 FROM pg_roles WHERE rolname = %(u)s"
        named_args: { u: "{{ user_pgwatch }}" }
      register: pgw_exists

    - name: "[pgwatch2] É membro de pg_monitor?"
      when: pt_exists.rowcount|int > 0
      community.postgresql.postgresql_query:
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ admin_user }}"
        login_db: "{{ db_name }}"
        query: "SELECT pg_has_role(%(u)s, 'pg_monitor', 'member') AS is_member"
        named_args: { u: "{{ user_pgw }}" }
      register: pgw_pgmonitor

    - name: "[pgwatch2] Tem atributo LOGIN?"
      when: pgw_exists.rowcount|int > 0
      community.postgresql.postgresql_query:
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ admin_user }}"
        login_db: "{{ db_name }}"
        query: "SELECT rolcanlogin FROM pg_roles WHERE rolname = %(u)s"
        named_args: { u: "{{ user_pgwatch }}" }
      register: pgw_login

    ### RESULTADOS
    - name: Resultado - powertuning
      ansible.builtin.debug:
        msg:
          - "Existe? {{ (pt_exists.rowcount|int > 0) | ternary('SIM','NÃO') }}"
          - "Tem pgmonitor?: {{ ((pt_pgmonitor.query_result|default([{'is_member': false}]))[0].is_member | default(false)) | ternary('SIM','NÃO') }}"
          - "CREATEROLE?: {{ ((pt_createrole.query_result|default([{'rolcreaterole': false}]))[0].rolcreaterole | default(false)) | ternary('SIM','NÃO') }}"
          - "LOGIN?: {{ ((pt_login.query_result|default([{'rolcanlogin': false}]))[0].rolcanlogin | default(false)) | ternary('SIM','NÃO') }}"

    - name: Resultado - pgwatch2
      ansible.builtin.debug:
        msg:
          - "Existe? {{ (pgw_exists.rowcount|int > 0) | ternary('SIM','NÃO') }}"
          - "Tem pgmonitor?: {{ ((pgw_pgmonitor.query_result|default([{'is_member': false}]))[0].is_member | default(false)) | ternary('SIM','NÃO') }}"
          - "LOGIN?: {{ ((pgw_login.query_result|default([{'rolcanlogin': false}]))[0].rolcanlogin | default(false)) | ternary('SIM','NÃO') }}"
