- name: Verificar usuários e permissões no Postgres (usando .pgpass)
  hosts: localhost
  gather_facts: no

  vars:
    db:
      host: "pg-db1"
      port: 5432
      name: "postgres"
      user: "postgres"
    role_powertuning: "powertuning"
    user_monitoramento: "pgwatch2"
    users_consutores:
      - "powertuning"
      - "pgwatch2"

  module_defaults:
    community.postgresql.postgresql_query:
      login_host: "{{ db.host }}"
      login_port: "{{ db.port }}"
      login_db: "{{ db.name }}"
      login_user: "{{ db.user }}"

  tasks:
    - name: Checa conection
      include_tasks: "./tasks/db_connection_teste.yml"

    - name: "[role powertuning] tem login?"
      include_tasks: "./tasks/role_existe.yml"
      vars:
        user_to_check: "{ { role_powertuning } }"

    - name: "[role powertuning] tem pgmonitor?"
      include_tasks: "./tasks/role_tem_pgmonitor.yml"
      vars:
        user_to_check: "{ { role_powertuning } }"
