- name: Verificar usuários e permissões no Postgres (usando .pgpass)
  hosts: localhost
  gather_facts: no

  vars:
    db:
      host: "pg-db1"
      port: 5432
      name: "postgres"
      user: "postgres"
    user_pt: "powertuning"
    user_pgwatch: "pgwatch2"
    users_consutores:
      - "powertuning"
      - "pgwatch2"

  module_defaults:
    community.postgresql.postgresql_query:
      login_host: "{{ db.host }}"
      login_port: "{{ db.port }}"
      login_db: "{{ db.name }}"
      login_user: "{{ db.user }}"

  tasks:
    - name: Checa conection
      include_tasks: "./tasks/db_connection_teste.yml"
    - name: "[powertuning] tem login?"
      include_tasks: "./tasks/permissao_pode_logar.yml"
    - name: "[powertuning] tem pgmonitor?"
      include_tasks: "./tasks/permissao_tem_pgmonitor.yml"
