- name: Verificar usuários e permissões no Postgres (usando .pgpass)
  hosts: localhost
  gather_facts: no
  vars:
    db:
      - host: "pg-db1"
      - port: 5432
      - name: "postgres"
      - user: "postgres"

    user_pt: "powertuning"
    user_pgwatch: "pgwatch2"
    users_consutores:
      - "powertuning"
      - "pgwatch2"

  tasks:
    - name: Checa conection
      include_tasks: "./tasks/db_connection_teste.yaml"
