- name: Verificando conexão nas portas do MONITORAMENTO
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Testa porta {{ item }}
      ansible.builtin.wait_for:
        host: "localhost"
        port: "{{ item }}"
        timeout: 1 
        state: started
      loop: 
        - 22
        - 3000
        - 5432
        - 8080
        - 9090
        - 9100
      register: resultado
      ignore_errors: yes


- name: Verificando conexão nas portas dos NODES LINUX
  hosts: "onprimise:aws_ec2"
  gather_facts: no
  tasks:
    - name: testa porta {{ item }}
      ansible.builtin.wait_for:
        port: "{{ item }}"
        timeout: 1
        state: started
      loop:
        - 22
        - 5432
        - 9100
      ignore_errors: yes

- name: Verificando conexão nas portas do NODES PROVISIONADOS
  hosts: aws_rds
  gather_facts: no
  tasks:
    - name: testa porta {{ item }}
      ansible.builtin.wait_for:
        port: "{{ item }}"
        timeout: 1
        state: started
      loop:
        - 5432
      ignore_errors: yes